# KDE Config File
[Desktop Entry]
Type=Application
Exec=@CMAKE_INSTALL_PREFIX@/bin/krfb-virtualmonitor
Icon=krfb
Terminal=false
Name=KRFBs Virtual Monitor
Name[ca]=Monitor virtual del Krfb
Name[ca@valencia]=Monitor virtual de Krfb
Name[cs]=Virtuální monitor KRFB
Name[el]=Εικονική οθόνη του KRFB
Name[en_GB]=KRFBs Virtual Monitor
Name[eo]=Virtuala Monitoro de KRFB
Name[es]=Monitor virtual de KRFB
Name[eu]=KRFBren alegiazko monitorea
Name[fi]=KRFB:n virtuaalinäyttö
Name[fr]=Moniteur virtuel « Krfb »
Name[gl]=Monitor virtual de KRFB
Name[ia]=Virtual Monitor de KRFB
Name[it]=Monitor virtuale di KRFB
Name[ka]=KRFB-ის ვირტუალური ეკრანი
Name[ko]=KRFBs 가상 모니터
Name[nl]=Virtuele monitor van KRFB
Name[pl]=Monitor wirtualny KRFB
Name[pt]=Monitor Virtual do KRFB
Name[pt_BR]=Monitor virtual do KRFB
Name[ro]=Monitor virtual KRFB
Name[ru]=Виртуальный монитор KRFB
Name[sk]=Virtuálny monitor KRFB
Name[sl]=Navidezni monitor KRFB
Name[sv]=Krfb:s virtuella bildskärm
Name[tr]=KRFB Sanal Monitörü
Name[uk]=Віртуальний монітор KRFB
Name[x-test]=xxKRFBs Virtual Monitorxx
Name[zh_CN]=KRBs 虚拟监视器
Comment=Remote Virtual Monitor
Comment[ca]=Monitor virtual remot
Comment[ca@valencia]=Monitor virtual remot
Comment[cs]=Vzdálený virtuální monitor
Comment[el]=Απομακρυσμένη εικονική οθόνη
Comment[en_GB]=Remote Virtual Monitor
Comment[eo]=Fora Virtuala Monitoro
Comment[es]=Monitor virtual remoto
Comment[eu]=Urruneko alegiazko monitorea
Comment[fi]=Virtuaalinen etänäyttö
Comment[fr]=Moniteur virtuel distant
Comment[gl]=Monitor virtual remoto
Comment[ia]=Monitor Virtual Remote
Comment[it]=Monitor virtuale remoto
Comment[ka]=დაშორებული ვირტუალური ეკრანი
Comment[ko]=원격 가상 모니터
Comment[nl]=Virtual Monitor op afstand
Comment[pl]=Zdalny monitor wirtualny
Comment[pt]=Monitor Virtual Remoto
Comment[pt_BR]=Monitor virtual remoto
Comment[ro]=Monitor virtual distant
Comment[ru]=Удалённый виртуальный монитор
Comment[sk]=Vzdialený virtuálny monitor
Comment[sl]=Oddaljeni navidezni monitor
Comment[sv]=Virtuell fjärrbildskärm
Comment[tr]=Uzak Sanal Monitör
Comment[uk]=Віддалений віртуальний монітор
Comment[x-test]=xxRemote Virtual Monitorxx
Comment[zh_CN]=远程虚拟监视器
NoDisplay=true
X-KDE-Wayland-Interfaces=zkde_screencast_unstable_v1
